# -----------------------Basic Understanding of Numpy Library------------------------------


In [1]:
'''
1. Linear algebra library in python.
2. Used for performing mathematical and logical operations on Array.
3. Provides features for operations on multidimensional array and matrices in python.
'''

'\n1. Linear algebra library in python.\n2. Used for performing mathematical and logical operations on Array.\n3. Provides features for operations on multidimensional array and matrices in python.\n'

# ----------------------How to create Numpy Array-------------------------------

In [2]:
# 1D Array
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# 2D Array
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [4]:
# ND array object
'''
1. Most important object defined in NumPy is an N-Dimensional array type called ndarray.
2. Describe the collection of object in same type.
3. Items can be accessed using Zero-based index.
4. Every item in an ndarray takes the same size of block in the memory.
5. Each element in the ndarray is an object of datatype object(called dtype).
'''

'\n1. Most important object defined in NumPy is an N-Dimensional array type called ndarray.\n2. Describe the collection of object in same type.\n3. Items can be accessed using Zero-based index.\n4. Every item in an ndarray takes the same size of block in the memory.\n5. Each element in the ndarray is an object of datatype object(called dtype).\n'

# ----------------------------Numpy Array Initializaion------------------------------------------

In [5]:
# Initialize Numpy Array
# xXy dimension with Zeros
import numpy as np
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
# Arranging numbers between x and y with an interval of z
import numpy as np
np.arange(10, 25, 5)

array([10, 15, 20])

In [7]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [9]:
# Arranging z numbers between x and y
np.linspace(5,10,6)
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [10]:
# Filling same numer in a array of dimension xXy
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [11]:
np.full((4,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [13]:
# Filling random number in a array of dimension xXy
np.random.random((2,2))

array([[0.02165854, 0.07679569],
       [0.71568908, 0.10301092]])

# --------------------------------Numpy Array inspection ---------------------------

In [16]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [17]:
# Return the shape of array
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
a.shape

(3, 3)

In [18]:
# customize the shape of array
a.shape = (9,1) 

In [20]:
# Find the size of array
a.size

9

In [24]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
a.size

24

In [25]:
# Find the dimension of array
a.ndim

1

In [28]:
# reshape the array
b = a.reshape(2,4,3)
b

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [29]:
b.ndim

3

In [31]:
# Return datatype of an array
a = np.arange(24, dtype=float)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [32]:
a.size

24

In [33]:
a.dtype

dtype('float64')

In [35]:
b = a.reshape(3,4,2)
b

array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.],
        [12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.],
        [20., 21.],
        [22., 23.]]])

# -------------------------Numpy Array Mathematics -----------------------------------------

In [36]:
# Can we perform some mathematical function using numpy

In [37]:
'''
Additin
subtract
divide
multiply
exp
sqrt
sin
cos
log
'''

'\nAdditin\nsubtract\ndivide\nmultiply\nexp\nsqrt\nsin\ncos\nlog\n'

In [38]:
# Addition
import numpy as np
np.sum([10,20])

30

In [39]:
a,b=10,20
np.sum([a,b])

30

In [40]:
np.sum([[0,1],[0,5]], axis=0)

array([0, 6])

In [41]:
np.sum([[0,1],[0,5]],axis=1)

array([1, 5])

In [45]:
a,b=30,20
np.subtract(a,b)

10

In [46]:
np.divide(a,b)

1.5

In [47]:
np.multiply(a,b)

600

In [48]:
np.exp(a)

10686474581524.463

In [49]:
np.sqrt(a)

5.477225575051661

In [50]:
np.sin(a)

-0.9880316240928618

In [51]:
np.cos(a)

0.15425144988758405

In [52]:
np.log(a)

3.4011973816621555

# --------------------- Array Comparision ----------------------------------------

In [56]:
# Element-wise comparison
import numpy as np
a = [1,2,3]
b = [1,2,3]
c = [1,2,4]
np.equal(a,b)
np.equal(a,c)

array([ True,  True, False])

In [57]:
# Array-wise comparison
np.array_equal(a,b)

True

# ----------------------Aggregate Function ---------------------------------

In [59]:
import numpy as np
a = [1,2,4]
b = [2,4,4]
c = [1,2,4]

In [60]:
# Arraywise sum
np.sum(a)

7

In [61]:
# Min of array
np.min(a)

1

In [62]:
# Mean of array
np.mean(a)

2.3333333333333335

In [63]:
# Median of array
np.median(a)

2.0

In [64]:
# Coorelation
np.corrcoef(a)

1.0

In [65]:
# Standard Deviation
np.std(a)

1.247219128924647

# ------------------------ Concept of Broadcasting --------------------------------

In [67]:
import numpy as np
a = np.array([[0,0,0],
             [10,10,10],
             [20,20,20],
             [30,30,30]])
b = np.array([0,1,2])
print('first Array:\n',a,'\n')
print('Second Array:\n',b,'\n')
print('First Array + Second Array:\n',a+b)

first Array:
 [[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] 

Second Array:
 [0 1 2] 

First Array + Second Array:
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


# ----------------------- Indexing and Slicing in Numpy Array ---------------------------------

In [68]:
#"How to select certain element of array"
# Index refers to a position of elemnt in array
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
a[0] #Show the first row

array([1, 2, 3])

In [84]:
a[:1] # Show the first row

array([[1, 2, 3]])

In [71]:
a[:1,1:] # Show first row apart first column

array([[2, 3]])

In [72]:
a[:2] # row till 2

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
a[:2,1:] # row till 2 and colum after 0

array([[2, 3],
       [5, 6]])

In [74]:
a[1:] # row after 0 

array([[4, 5, 6],
       [7, 8, 9]])

In [75]:
a[1:,1:] # row after 0 and colum after 0

array([[5, 6],
       [8, 9]])

In [76]:
a[:2,1:] # row till 2 and column after 1

array([[2, 3],
       [5, 6]])

In [77]:
a[2] # row third

array([7, 8, 9])

In [78]:
a[2,:] # row third

array([7, 8, 9])

In [79]:
a[2:,:] # row third

array([[7, 8, 9]])

In [80]:
a[:,:2] # all row apart first column

array([[1, 2],
       [4, 5],
       [7, 8]])

In [81]:
a[1,:2] # row 2nd and colum after 2

array([4, 5])

In [82]:
a[1:2,:2]

array([[4, 5]])

# ----------------------Array Manipulations -------------------------------------------------

In [92]:
# What are the various manipulations done within the array
a = [1,2,3]
b = [2,3,4]

In [93]:
# Concatenating two array together:
np.concatenate((a,b))

array([1, 2, 3, 2, 3, 4])

In [95]:
# Stack array row_wise (vertically)
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [96]:
# Stack array column wise (horizontally)
np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

In [97]:
# combining column wise stacked array
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [100]:
# Splitting Array
x = np.arange(16.0).reshape(4,4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [101]:
np.hsplit(x,2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]), array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [103]:
np.hsplit(x, np.array([3,6]))

[array([[ 0.,  1.,  2.],
        [ 4.,  5.,  6.],
        [ 8.,  9., 10.],
        [12., 13., 14.]]), array([[ 3.],
        [ 7.],
        [11.],
        [15.]]), array([], shape=(4, 0), dtype=float64)]

# -------------Advantage of Numpy Array over List -------------------------

In [104]:
"Why should i use numpy if i already have a list"

'Why should i use numpy if i already have a list'

In [105]:
# Consumes less memory
# Faster
# More convenient

# ---------------------Numpy Vs List (Memory Size)----------------------------------

In [106]:
import numpy as np
import sys

In [110]:
l = range(1000)
s_l = sys.getsizeof(10)*len(l)

In [109]:
array = np.arange(1000)
s_a = array.size*array.itemsize

In [116]:
print("Consumed memory by list:",s_l)
print("Consumed memory by Numpy Array:",s_a)
print("More memory used by list over numpy:",(s_l-s_a))

Consumed memory by list: 28000
Consumed memory by Numpy Array: 4000
More memory used by list over numpy: 24000


In [ ]:
# ------------------